sudo: false
language: scala
notifications:
  irc:
    channels:
      - "irc.freenode.org#argonaut"
    skip_join: true
    template:
      - "\x0313argonaut\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
script:
- sbt ++${TRAVIS_SCALA_VERSION} test:compile jvmParent/test "project jsParent" testSequential
matrix:
  include:
    - jdk: oraclejdk8
      scala: 2.11.12

    - jdk: openjdk11
      scala: 2.12.8

    - jdk: oraclejdk8
      scala: 2.12.8

    - jdk: oraclejdk8
      scala: 2.13.0-M5

    - scala: 2.11.12
      jdk: oraclejdk8
      sudo: required
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -
      script:
      - sbt ++$TRAVIS_SCALA_VERSION nativeTest/nativeLink
      - ./native-test/target/scala-2.11/nativetest-out
