sudo: false
language: scala
scala:
   - 2.10.6
   - 2.11.8
jdk:
  - oraclejdk8
  - openjdk7
notifications:
  irc:
    channels:
      - "irc.freenode.org#argonaut"
    skip_join: true
    template:
      - "\x0313argonaut\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
script:
- sbt ++${TRAVIS_SCALA_VERSION} mimaReportBinaryIssues test
matrix:
  include:
    - jdk: oraclejdk8
      scala: 2.12.1
      script: sbt ++${TRAVIS_SCALA_VERSION} mimaReportBinaryIssues test
