sudo: false
language: scala
scala:
   - 2.10.4
   - 2.11.6
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
script:
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues test
notifications:
  irc:
    channels:
      - "irc.freenode.org#argonaut"
    skip_join: true
    template:
      - "\x0313argonaut\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
