language: scala
scala:
   - 2.10.3
   - 2.11.2
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
notifications:
  irc:
    channels:
      - "irc.freenode.org#argonaut"
    skip_join: true
    template:
      - "\x0313argonaut\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
